#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-org.osgi.core
Version  : 4.1.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.1.0/org.osgi.core-4.1.0.jar
Source0  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.1.0/org.osgi.core-4.1.0.jar
Source1  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.1.0/org.osgi.core-4.1.0.pom
Source2  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar
Source3  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.pom
Source4  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.jar
Source5  : https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-org.osgi.core-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-org.osgi.core package.
Group: Data

%description data
data components for the mvn-org.osgi.core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0/org.osgi.core-4.1.0.jar
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.1.0/org.osgi.core-4.1.0.pom
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.pom
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.jar
/usr/share/java/.m2/repository/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.pom
